In [1]:
import PQC
from qiskit import Aer
import numpy as np
from torchvision import datasets, transforms
import torch
from torch.autograd import Variable
from QuanvolutionLayerFile import *

In [2]:
Aer.backends()

[QasmSimulator(
 backend_name='qasm_simulator', provider=AerProvider()),
 StatevectorSimulator(
 backend_name='statevector_simulator', provider=AerProvider()),
 UnitarySimulator(
 backend_name='unitary_simulator', provider=AerProvider()),
 PulseSimulator(
 backend_name='pulse_simulator', provider=AerProvider())]

In [3]:
# Run the quantum circuit on a statevector simulator backend
backend = Aer.get_backend('qasm_simulator')
qc = PQC.QuantumCircuit(backend=backend)

In [4]:
print(torch.rand(1,27))
print(qc.run(data=None,params_tensor=torch.rand(27)))

tensor([[0.0419, 0.9230, 0.2382, 0.9343, 0.9175, 0.3756, 0.8122, 0.0730, 0.2279,
         0.9076, 0.9806, 0.6279, 0.4913, 0.3826, 0.9358, 0.9347, 0.6881, 0.6304,
         0.0402, 0.3075, 0.1624, 0.5268, 0.1311, 0.1605, 0.1937, 0.4899, 0.7575]])
[0.0]


In [5]:
BATCH_SIZE = 16

In [6]:
train_dataset = datasets.MNIST(root = "./data",
                               train = True,
                               download = True,
                               transform = transforms.ToTensor())

test_dataset = datasets.MNIST(root = "./data",
                              train = False,
                              transform = transforms.ToTensor())

train_loader = torch.utils.data.DataLoader(dataset = train_dataset,
                                           batch_size = BATCH_SIZE,
                                           shuffle = True)

test_loader = torch.utils.data.DataLoader(dataset = test_dataset,
                                          batch_size = BATCH_SIZE,
                                          shuffle = False)

In [7]:
print(train_dataset)

Dataset MNIST
    Number of datapoints: 60000
    Root location: ./data
    Split: Train
    StandardTransform
Transform: ToTensor()


In [8]:
for x_train, y_train in train_loader:
    print(x_train.size(),y_train.size())
    break

torch.Size([16, 1, 28, 28]) torch.Size([16])


In [9]:
ql = QuanvolutionLayer(out_channels=1,kernel_size=3,backend=backend)
print(ql.weight)
for x_train, y_train in train_loader:
    print(x_train.size(),y_train.size())
    processed = ql.forward(inputs=x_train)
    print(processed)
    break


tensor([[0.2290, 5.4919, 2.6511, 4.1390, 5.9203, 3.6461, 4.1323, 3.4057, 3.5971,
         1.3234, 4.2845, 3.5236, 5.2068, 0.0103, 4.4404, 2.1332, 0.1266, 3.2594,
         4.9872, 2.0798, 3.3668, 0.7462, 1.3633, 2.9587, 5.1442, 3.7783, 0.3176]])
torch.Size([16, 1, 28, 28]) torch.Size([16])
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
tensor([[[[0.0107, 0.0205, 0.0137,  ..., 0.0195, 0.0146, 0.0146],
          [0.0176, 0.0068, 0.0186,  ..., 0.0137, 0.0137, 0.0195],
          [0.0117, 0.0186, 0.0176,  ..., 0.0107, 0.0098, 0.0156],
          ...,
          [0.0127, 0.0166, 0.0234,  ..., 0.0186, 0.0088, 0.0078],
          [0.0146, 0.0117, 0.0137,  ..., 0.0107, 0.0244, 0.0117],
          [0.0176, 0.0146, 0.0107,  ..., 0.0137, 0.0205, 0.0186]]],


        [[[0.0146, 0.0225, 0.0137,  ..., 0.0195, 0.0205, 0.0225],
          [0.0146, 0.0156, 0.0195,  ..., 0.0107, 0.0234, 0.0215],
          [0.0166, 0.0107, 0.0137,  ..., 0.0117, 0.0146, 0.0107],
          ...,
          [0.0195, 0.0137, 0.0098,  ..., 0.0205, 0

In [10]:
print(processed.size())

torch.Size([16, 1, 26, 26])
